# Generated by Django 4.1 on 2024-04-20 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasosapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfacility',
            name='kepemilikan',
            field=models.CharField(choices=[('Dikelola Pemerintah', 'Dikelola Pemerintah'), ('Dikelola Swasta', 'Dikelola Swasta'), ('Dikelola Organisasi Sosial', 'Dikelola Organisasi Sosial'), ('Belum Mengisi Penyelenggara', 'Belum Mengisi Penyelenggara'), ('-', '-')], default='Belum Mengisi Penyelenggara', max_length=50),
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='koderumahsakit',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalfacility',
            name='tipe',
            field=models.CharField(choices=[('Rumah Sakit', 'Rumah Sakit'), ('Puskesmas', 'Puskesmas'), ('Klinik', 'Klinik'), ('Apotik', 'Apotik')], default='Rumah Sakit', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='hari_beroperasi',
            field=models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], default='Setiap Hari', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='jenis',
            field=models.CharField(choices=[('Rumah Sakit Umum', 'Rumah Sakit Umum'), ('Rumah Sakit Khusus', 'Rumah Sakit Khusus'), ('-', '-')], default='Rumah Sakit Umum', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalfacility',
            name='tingkatan',
            field=models.CharField(choices=[('Kelas A', 'Kelas A'), ('Kelas B', 'Kelas B'), ('Kelas C', 'Kelas C'), ('Belum Mengisi Tingkatan', 'Belum Mengisi Tingkatan'), ('-', '-')], default='Belum Mengisi Tingkatan', max_length=50),
        ),
    ]
