# Generated by Django 4.1 on 2024-04-25 09:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fasosapp', '0002_medicalfacility_kepemilikan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernmentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Perangkat Daerah', 'Perangkat Daerah'), ('Instansi Vertikal', 'Instansi Vertikal')], default='Perangkat Daerah', max_length=50)),
                ('alamat', models.TextField(max_length=255)),
                ('no_telp', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Perencanaan/Pengajuan', 'Perencanaan/Pengajuan'), ('Dalam Masa Peninjauan', 'Dalam Masa Peninjauan'), ('Perencanaan Dibatalkan', 'Perencanaan Dibatalkan'), ('Dalam Masa Pembangunan', 'Dalam Masa Pembangunan'), ('Pembangunan Selesai/Belum Beroperasi', 'Pembangunan Selesai/Belum Beroperasi'), ('Pembangunan Selesai/Sudah Beroperasi', 'Pembangunan Selesai/Sudah Beroperasi'), ('Tutup/Sudah Tidak Beroperasi', 'Tutup/Sudah Tidak Beroperasi')], default='Perencanaan/Pengajuan', max_length=50)),
                ('hari_beroperasi', models.CharField(choices=[('Setiap Hari', 'Setiap Hari'), ('Senin - Jumat', 'Senin - Jumat'), ('Sabtu - Minggu', 'Sabtu - Minggu')], max_length=50)),
                ('jam_beroperasi', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(upload_to='local_government_office')),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
