# Generated by Django 4.1 on 2024-04-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasosapp', '0003_localgovernmentoffice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localgovernmentoffice',
            old_name='jenis',
            new_name='tipe',
        ),
    ]
