# Generated by Django 4.1 on 2024-04-26 22:53

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fasosapp', '0005_alter_localgovernmentoffice_nama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCTVETLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_cam', models.CharField(max_length=50)),
                ('nama_lokasi', models.TextField(max_length=150)),
                ('tipe', models.CharField(choices=[('Perangkat Keamanan Pemerintah Daerah - CCTV', 'Perangkat Keamanan Pemerintah Daerah- CCTV'), ('Perangkat Keamanan Instansi Vertikal - CCTV', 'Perangkat Keamanan Instansi Vertikal- CCTV')], default='Perangkat Keamanan Pemerintah Daerah - CCTV', max_length=50)),
                ('wilayah', models.CharField(choices=[('Polsek Balaraja', 'Polsek Balaraja'), ('Polsek Kresek', 'Polsek Kresek'), ('Polsek Mauk', 'Polsek Mauk'), ('Polsek Kronjo', 'Polsek Kronjo'), ('Polsek Pasar Kemis', 'Polsek Pasar Kemis'), ('Polsek Tigaraksa', 'Polsek Tigaraksa'), ('Polsek Panongan', 'Polsek Panongan'), ('Polsek Cikupa', 'Polsek Cikupa'), ('Polsek Cisoka', 'Polsek Cisoka'), ('Polresta Tangerang', 'Polresta Tangerang')], default='Polresta Tangerang', max_length=100)),
                ('sn_camera', models.CharField(max_length=100)),
                ('sn_modem', models.CharField(max_length=100)),
                ('tgl_pemasangan', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('photo', models.ImageField(upload_to='local_government_office')),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
