# Generated by Django 4.1 on 2024-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasosapp', '0006_cctvetle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvetle',
            name='photo',
            field=models.ImageField(upload_to='cctv_etle'),
        ),
    ]
