# Generated by Django 4.1 on 2024-04-27 12:34

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fasosapp', '0007_alter_cctvetle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvetle',
            name='tgl_pemasangan',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='BatasKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=150)),
                ('kd_kcmtan', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('date_field', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
