# Generated by Django 4.1 on 2024-04-27 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fasosapp', '0007_alter_cctvetle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatasKecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(max_length=150)),
                ('kd_kcmtan', models.CharField(max_length=20)),
                ('tipe', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='cctvetle',
            name='tgl_pemasangan',
            field=models.DateField(),
        ),
    ]
